pool:
  name: belajar
  demands:
  - myCustomCapability   # check for existence of capability
  - agent.os -equals Darwin  # check for specific string in capability
  displayName: 'Run a multi-line script'
